Housekeeping - Gradle, License, etc
elytra/Smores pull request #6
Opened 2017-08-07 21:56 UTC by jamierocks

- Rewrote the Gradle buildscripts
  - Bumped Gradle wrapper to 4.1
  - Removed the MDK junk
  - Updated the MCP mappings to more recent ones
- Fixed license headers
- Produced, using gitignore.io, an improved .gitignore file
- Added a .gitattributes file to ensure Git diffs files correctly
- Move constants to a SmoresConstants class

2017-08-08 00:39 UTC, darkevilmac commented
> Move constants to a SmoresConstants class

but why tho

2017-08-08 00:41 UTC, jamierocks commented
> but why tho

Simply put, I prefer to separate my constants away where they are on their own.

2017-08-08 04:19 UTC, falkreon requested changes
Overall, a good change. Some of this formatting needed to happen. Some of it really, really didn't. Let's chop this down to what needs to be done.

2017-08-08 04:19 UTC, falkreon commented on src/main/java/com/elytradev/smores/Smores.java
> +@Mod(
If you really want to put things where they go:
*  Strings that can be localized go in the lang file. In this case, none of them
*  Strings that specify part of the build configuration, such as the version, go in the build file and get replaced here.
*  Strings that can't be localized, but fall logically within the scope of this object, belong in this object. In this case, modid, name, and guiFactory.

A SmoresConstants class would *only* contain Strings that belong somewhere else.

2017-08-08 04:19 UTC, falkreon commented on src/main/java/com/elytradev/smores/Smores.java
> +    public static final Logger log = LogManager.getLogger(SmoresConstants.NAME);
either Smores.class.getName() or Smores.NAME

2017-08-08 04:19 UTC, falkreon commented on src/main/java/com/elytradev/smores/Smores.java
> -
We're just going to need to put this IMC hook back in for ore voting.

2017-08-08 04:19 UTC, falkreon commented on src/main/java/com/elytradev/smores/SmoresConstants.java
> +/*
no.

2017-08-08 04:19 UTC, falkreon commented on src/main/java/com/elytradev/smores/item/ItemBase.java
> +    {
Hanging braces need to be fixed in this class.

2017-08-08 04:19 UTC, falkreon commented on src/main/java/com/elytradev/smores/Smores.java
> +    public static final Logger log = LogManager.getLogger(SmoresConstants.NAME);
Also, log is static final. It should be LOG.

2017-08-08 11:55 UTC, jamierocks commented on src/main/java/com/elytradev/smores/Smores.java
> +@Mod(
Fair enough, I'll move them back into `Smores`.

2017-08-08 11:58 UTC, jamierocks commented on src/main/java/com/elytradev/smores/Smores.java
> +    public static final Logger log = LogManager.getLogger(SmoresConstants.NAME);
Using lowercase for `Logger`s is a convention I have long been accustomed to. Forge also follow this convention - https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/FMLLog.java#L40.

2017-08-08 11:59 UTC, jamierocks commented on src/main/java/com/elytradev/smores/Smores.java
> -
The handler did nothing, and would be trivial to rewrite.

2017-08-08 11:59 UTC, jamierocks commented on src/main/java/com/elytradev/smores/item/ItemBase.java
> +    {
I did not introduce the hanging braces, but perhaps it falls under the directive of this pr to resolve.

2017-08-09 06:47 UTC, falkreon approved these changes

2017-08-09 06:49 UTC, merged